
insert into usuarios (enable, password, rol, unlocked, username, verification_code, notificar_correo)
 values (false, 'nohay', 3, false, 'OtraInstitucion', null, false),
(true, 'falsa', 3, true, 'usc@usc.es', null, false),
(true, 'falsa', 3, true, 'uvigo@uvigo.es', null, false);

insert into instituciones (color, direccion, nombre, visibilidad, webpage, usuario_username, colorbandas, letrasblancas, letrasblancasbandas)
 values ('#5AB9EA', null, 'Otra', false, null, 'OtraInstitucion', '#5AB9EA', false, false),
('#3733FF', null, 'USC', true, null, 'usc@usc.es', '#C5C5C5', true, false),
('#FF2513', null, 'UVigo', true, null, 'uvigo@uvigo.es', null, false, false);


INSERT INTO nivelestudios (nivelestudios) VALUES ('Basica'), ('Secundaria'), ('Tecnico'), ('Bachillerato'),
('Graduado'), ('Master'), ('Doctorado'), ('Otros');

insert into areas (area)
 values ('Álgebra'),
('Análisis Geográfico Regional'),
('Análisis Matemático'),
('Anatomía Patológica'),
('Anatomía Y Anatomía Patológica Comparada'),
('Anatomía Y Embriología Humana'),
('Antropología Social'),
('Arqueología'),
('Arquitectura Y Tecnología De Computadores'),
('Biblioteconomía Y Documentación'),
('Biología Celular'),
('Bioquímica Y Biología Molecular'),
('Botánica'),
('Ciencias De Materiales E Ingeniería Metalúrgica'),
('Ciencias Y Técnicas Historiográficas'),
('Cirugía'),
('Comercialización E Investigación De Mercados'),
('Comunicación Audiovisual Y Publicidad'),
('Construcciones Arquitectónicas'),
('Cristalografía Y Mineralogía'),
('Derecho Administrativo'),
('Derecho Civil'),
('Derecho Constitucional'),
('Derecho Del Trabajo Y De La Seguridad Social'),
('Derecho Eclesiástico Del Estado'),
('Derecho Financiero Y Tributario'),
('Derecho Internacional Privado'),
('Derecho Internacional Pco.Y Relac. Internacionales'),
('Derecho Mercantil'),
('Derecho Penal'),
('Derecho Procesal'),
('Derecho Romano'),
('Dermatología'),
('Dibujo'),
('Didáctica De La Expresión Corporal'),
('Didáctica De La Expresión Musical'),
('Didáctica De La Expresión Plástica'),
('Didáctica De La Lengua Y La Literatura'),
('Didáctica De Las Matemáticas'),
('Didáctica De Las Ciencias Experimentales'),
('Didáctica De Las Ciencias Sociales'),
('Didáctica Y Organización Escolar'),
('Ecología'),
('Economía Aplicada'),
('Economía Financiera Y Contabilidad'),
('Edafología Y Química Agrícola'),
('Educación Física Y Deportiva'),
('Electrónica'),
('Enfermería'),
('Estadística E Investigación Operativa'),
('Estudios Árabes E Islámicos'),
('Expresión Gráfica Arquitectónica'),
('Expresión Gráfica En La Ingeniería'),
('Farmacología'),
('Filología Alemana'),
('Filología Española'),
('Filología Francesa'),
('Filología Griega'),
('Filología Inglesa'),
('Filología Italiana'),
('Filología Latina'),
('Filologías Gallega Y Portuguesa'),
('Filosofía'),
('Filosofía Del Derecho'),
('Física Aplicada'),
('Física Atómica, Molecular Y Nuclear'),
('Física De La Materia Condensada'),
('Física De La Tierra'),
('Física De La Tierra, Astronomía Y Astrofísica'),
('Física Teórica'),
('Fisiología'),
('Fisiología Vegetal'),
('Fisioterapia'),
('Fundamentos Del Análisis Económico'),
('Genética'),
('Geografía Física'),
('Geografía Humana'),
('Geometría Y Topología'),
('Historia Antigua'),
('Historia Contemporánea'),
('Historia De América'),
('Historia De La Ciencia'),
('Historia Del Arte'),
('Historia Del Derecho Y De Las Instituciones'),
('Historia E Instituciones Económicas'),
('Historia Medieval'),
('Historia Moderna'),
('Ingeniería Agroforestal'),
('Ingeniería Cartográfica, Geodesia Y Fotogrametría'),
('Ingeniería De La Construcción'),
('Ingeniería De Los Procesos De Fabricación'),
('Ingeniería De Sistemas Y Automática'),
('Ingeniería Del Terreno'),
('Ingeniería E Infraestructura De Los Transportes'),
('Ingeniería Eléctrica'),
('Ingeniería Hidráulica'),
('Ingeniería Informática'),
('Ingeniería Mecánica'),
('Ingeniería Química'),
('Ingeniería Telemática'),
('Inmunología'),
('Lengua Española'),
('Lenguajes Y Sistemas Informáticos'),
('Lingüística General'),
('Literatura Española'),
('Máquinas Y Motores Térmicos'),
('Matemática Aplicada'),
('Mecánica De Fluidos'),
('Mecánica De Medios Contínuos Y Tª De Estructuras'),
('Medicina'),
('Medicina Legal Y Forense'),
('Medicina Preventiva Y Salud Pública'),
('Medicina Y Cirugía Animal'),
('Métodos De Investigación Y Diagnóstico En Educac.'),
('Microbiología'),
('Música'),
('Nutrición Y Bromatología'),
('Obstetricia Y Ginecología'),
('Oftalmología'),
('Óptica'),
('Organización De Empresas'),
('Otorrinolaringología'),
('Paleontología'),
('Parasitología'),
('Pediatría'),
('Personalidad, Evaluación Y Tratamiento Psicológic.'),
('Prehistoria'),
('Producción Animal'),
('Producción Vegetal'),
('Proyectos De Ingeniería'),
('Psicología Evolutiva Y De La Educación'),
('Psicología Social'),
('Psiquiatría'),
('Química Analítica'),
('Química Física'),
('Química Inorgánica'),
('Química Orgánica'),
('Radiología Y Medicina Física'),
('Sanidad Animal'),
('Sociología'),
('Tecnología De Los Alimentos'),
('Tecnología Electrónica'),
('Teoría De La Literatura Y Literatura Comparada'),
('Teoría De La Señal Y Comunicaciones'),
('Teoría E Historia De La Educación'),
('Toxicología'),
('Zoología'),
('Didáctica De Expresión Musical,Plástica Y Corporal'),
('Filosofía Del Derecho, Moral Y Política'),
('Filosofía Moral'),
('Tecnologías Del Medio Ambiente'),
('Periodismo'),
('Psicología Básica');








